# Generated by Django 5.2.7 on 2025-10-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='residence_status',
            field=models.CharField(choices=[('in_school', 'Lives in School'), ('not_in_school', 'Does not Live in School')], default='in_school', max_length=20),
        ),
    ]
